name: Build and push Docker Image to Docker Hub
on: push
jobs:
  push_to_registry:
    name: push docker image to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: check out the repo
        uses: actions/checkout@v3
      - name: login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Build and push docker image
        id: push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: sawantrohan732/nginx-server:latest

